name: CI-CD

on:
  push:
    branches:  ["mainteste"]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v3.1.0
    - name: construcao da imagem docker 
      uses: docker/build-push-action@v3.2.0
      with: 
           context: /.src
           file: ./src/Dockerfile
           push: true
           tags: |
               carlosarjunior/testescicd:v1
               carlosarjunior/testescicd:latest
  
               
             
           
           
        
        
        
        
      
    
