name: CI-CD

on:
  push:
    branches:  ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v3.1.0
    - name: construcao da imagem docker 
      uses: docker/build-push-action@v3.2.0
      with: 
           username: ${{secrets.DOCKERHUB_USER}}
           userpassword: ${{secrets.DOCKERHUB_PWD}}
           context: ./scr
           file: ./scr/Dockerfile
           push: true
           tags: |
               cjuniordocker/testescicd:v1
               cjuniordocker/testescicd:latest               
             
           
           
        
        
        
        
      
    
